config/routes.rb
Rails.application.routes.draw do
  root 'search#index'

  resources :bikes, only: :show do
    resource :booking, only: [:new, :create, :show]
  end
  resources :search, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  has_many :bookings
  has_many :unavailabilities
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :bike

  validates :date, :user_full_name, presence: true
  validate :today_or_in_future

  scope :on_date, ->(query_date) { where(date: query_date) }

  def today_or_in_future
    if date < Date.current
      errors.add(:date, "can't be in the past")
    end
  end
end

app/models/unavailability.rb
class Unavailability < ApplicationRecord
  belongs_to :bike
  validates :date, presence: true
  validates :date, uniqueness: { scope: :bike_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  def show
    @bike = Bike.find(bike_params[:id])
  end

  private

  def bike_params
    params.permit(:id)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking ||= Booking.new(bike_id: booking_params[:bike_id])
  end

  def create
    @booking = CreateBooking.run(
      bike_id: booking_params[:bike_id],
      date: booking_params[:date],
      user_full_name: booking_params[:user_full_name],
    )

    if @booking.persisted?
      message = "Thanks for your booking #{@booking.user_full_name.capitalize}. See you on #{@booking.date.strftime('%A, %e %b')}!"
      respond_to do |format|
        format.json { render json: { success_message: message }, status: :created }
      end
    else
      errors = @booking.errors.full_messages
      respond_to do |format|
        format.json { render json: { error_messages: errors }, status: :unprocessable_entity }
      end
    end
  end

  private

  def booking_params
    params.permit(:bike_id, :date, :user_full_name)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    # TODO: only get available bikes. Move to service
    @bikes = Bike.all

    respond_to do |format|
      format.html
      format.json { render json: @bikes }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/show.html.erb
<div class="wrapper--small">
  <div class="card">
    <%= render partial: "common/bike", locals: { bike: @bike } %>
    <div class="pt-6" [data-booking-form]>
      <%= button_to("Book", new_bike_booking_path(@bike.id), class: "button", method: :get) %>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="wrapper--small">
  <div class="card">
    <%= render partial: "common/bike", locals: { bike: @booking.bike } %>
    <%= form_with url: bike_booking_path, local: false, class: "pt-6", data: { booking_form: true } do |form| %>
      <%= form.hidden_field :bike_id, value: @booking.bike_id %>
      <div class="mb-4">
        <%= form.label :user_full_name, "Name" %>
        <%= form.text_field :user_full_name %>
      </div>
      <div class="mb-5">
        <%= form.label :date, "Date" %>
        <%= form.date_field :date, min: Date.today, value: Date.today %>
      </div>
      <div class="booking-errors" data-booking-errors>
      </div>
      <div>
        <%= form.submit "Book", class: "button" %>
      </div>
    <% end %>
    <div class="alert hidden mt-5" data-booking-alert></div>
  </div>
</div>

app/views/common/_bike.html.erb
<div class="image" style='background-image: url("<%= asset_url(bike.image_name) %>")'></div>
<div>
  <div class="font-bold capitalize mb-1"><%= bike.name.capitalize %></div>
  <div class="mb-2"><%= bike.description&.capitalize %></div>
  <div class="italic"><%= number_to_currency(bike.price_per_day) %> per day</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BikeNextDoor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      Bike Next Door
    </div>
    <div class="wrapper">
      <%= yield %>
    </div>
  </body>
</html>

app/views/search/index.html.erb
<div class="flex p-4" data-search-filters>
  <label class="mr-2">Order by:</label>
  <%= select_tag :order_by, options_for_select([ "Default", "Name", "Price" ], "Default"),
    { "data-search-order-by" => "true" }
  %>
</div>

<div class="flex p-4" data-date-filters>
  <label class="mr-2">Available on:</label>
  <%= date_field(:bike, :check_available, value: Date.today, min: Date.today) %>
</div>

<div class="search-bikes" data-search-bikes>
  <div class="w-full text-center italic p-2">
    Searching...
  </div>
</div>